services:
  express:
    container_name: express
    environment:
      - NODE_ENV=development
    build:
      context: .
    ports:
      - 3001:3001
    volumes:
      - ./stubs-server:/usr/express
      - express-node_modules:/usr/express/node_modules
    command: npm run start:dev
    links:
      - "mongo:db"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-persist-data:/data/db
    ports:
      - 27017:27017

volumes:
  express-node_modules:
  mongodb-persist-data:
